name: voice_assistant
description: "A sample AI Voice Assistant app built on LiveKit Agents"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  chat_bubbles: ^1.6.0
  livekit_client: ^2.4.1
  flutter_dotenv: ^5.2.1
  http: ^1.3.0
  provider: ^6.1.2
  livekit_components: 1.2.1
  flutter_background: ^1.3.0+1
  flutter_webrtc: ^0.13.1+hotfix.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
